export enum SubscriptionState {
  REGISTERED = "REGISTERED",
  PLAN_SELECTED = "PLAN_SELECTED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  ACTIVE = "ACTIVE",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED"
}
